# Generated by Django 2.2.5 on 2020-12-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201230_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='check_int',
            new_name='check_in',
        ),
    ]
